sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-system-dev libboost-thread-dev

script:
  - cmake --version
  - cmake .
  - make
